//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrderList
    {
        public int Order_No { get; set; }
        public string Supplier { get; set; }
        public string Stock_Site { get; set; }
        public string Stock_Name { get; set; }
        public string Order_Date { get; set; }
        public string Last_Update { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public string Country { get; set; }
        public string Post_Code { get; set; }
        public string Supplier_name { get; set; }
    }
}
